import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import './index.scss'
import { Providers } from "./providers";
import AppWrapper from "./AppWrapper";
import Header from "@/components/header/Header";
import SideBar from "@/components/SideBar";
import ScrollToTop from "@/components/ScrollToTop";
import HeroBanner from "./home/heroBanner/HeroBanner";
import SocialBar from "@/components/Ads/Social";
import DirectLink from "../components/Ads/DirectLink";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from '@vercel/speed-insights/next';
import SocialBarMe from "@/components/Ads.me/Social.me";
import DirectLinkMe from "@/components/Ads.me/DirectLink";
import Template from "@/components/Ads/Template";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Chikiimass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AppWrapper>
            <Template>
              <SideBar />
              <Analytics />
              <SocialBar />
              <SocialBarMe />
              <DirectLink />
              <DirectLinkMe />
              <Header />
              <ScrollToTop>
                {children}
                <SpeedInsights />
              </ScrollToTop>
              <HeroBanner />
            </Template>
          </AppWrapper>
        </Providers>
      </body>
    </html>
  );
}
