import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import './index.scss'
import { Providers } from "./providers";
import AppWrapper from "./AppWrapper";
import Header from "@/components/header/Header";
import SideBar from "@/components/SideBar";
import ScrollToTop from "@/components/ScrollToTop";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Chikiimass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AppWrapper>
            <SideBar />
            <Header />
            <ScrollToTop>
              {children}
            </ScrollToTop>
          </AppWrapper>
        </Providers>
      </body>
    </html>
  );
}
